name: Build Project

on:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Build Go Project
        run: ls -la ; cd cmd/apps && go build

      - name: Run Go Project
        run: cd cmd/apps && go run main.go
